# Generated by Django 6.0.2 on 2026-03-18 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_producto_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
