# Generated by Django 6.0.2 on 2026-03-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock',
            new_name='cantidad',
        ),
    ]
