# Generated by Django 6.0.2 on 2026-03-20 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_stock_stock_cantidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Compra',
        ),
    ]
