# Generated by Django 6.0.2 on 2026-03-20 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_producto_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stock'),
        ),
    ]
