# Generated by Django 6.0.2 on 2026-03-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_compra_producto_alter_stock_producto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Producto',
        ),
    ]
