# Generated by Django 6.0.2 on 2026-03-21 05:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_stock_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosProv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.now)),
                ('producto_pedido_new', models.CharField()),
                ('cantidad_pedida', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('producto_pedido_existente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.producto')),
            ],
        ),
    ]
