# Generated by Django 6.0.2 on 2026-03-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_pedidosprov'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosprov',
            name='tipo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
