# Generated by Django 6.0.2 on 2026-03-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_pedidosprov_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosprov',
            name='producto_pedido_existente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.producto'),
        ),
        migrations.AlterField(
            model_name='pedidosprov',
            name='producto_pedido_new',
            field=models.CharField(blank=True, null=True),
        ),
    ]
