# Generated by Django 6.0.2 on 2026-03-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_pedidosprov_producto_pedido_existente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('metro', 'Metro')], default='Unidad', max_length=20),
            preserve_default=False,
        ),
    ]
